// Run with: node_modules/.bin/electron tests/note.cjs
const { app, BrowserWindow } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'secretary-note-'));
app.setPath('userData', temporary);
app.whenReady().then(async () => {
  const window = new BrowserWindow({ show: false, webPreferences: { contextIsolation: true } });
  try {
    await window.loadFile(path.join(__dirname, '../src/renderer/index.html'));
    const result = await window.webContents.executeJavaScript(`(async () => {
      const assert = (condition, message) => { if (!condition) throw new Error(message); };
      setView('note');
      assert(!document.getElementById('note').classList.contains('hidden'), 'Note view visible');
      assert(document.getElementById('board').classList.contains('hidden'), 'Board hidden');
      const editor = document.getElementById('noteEditor');
      editor.value = '# Hello\\n\\n**bold**\\n\\n- [x] Done' + noteTable(2, 3);
      editor.dispatchEvent(new Event('input'));
      const preview = document.getElementById('notePreview');
      assert(preview.querySelector('h1').textContent === 'Hello', 'Heading rendered');
      assert(preview.querySelector('strong').textContent === 'bold', 'Formatting rendered');
      assert(preview.querySelectorAll('tbody tr').length === 2, 'Table rows');
      assert(preview.querySelectorAll('th').length === 3, 'Table columns');
      assert(preview.querySelector('input').disabled, 'Task checkbox passive');
      const direction = document.getElementById('noteDirection');
      direction.value = 'rtl'; direction.dispatchEvent(new Event('change'));
      assert(preview.dir === 'rtl' && editor.dir === 'rtl', 'RTL applies to both panes');
      assert(JSON.parse(localStorage.getItem(NOTE_KEY)).content === editor.value, 'Saved content');
      editor.setSelectionRange(editor.value.length, editor.value.length);
      document.getElementById('insertNoteTemplate').click();
      assert(editor.value.startsWith('# Hello') && editor.value.includes('# Meeting notes'), 'Template preserves content');
      const safe = renderNoteMarkdown('<script>alert(1)</script><img src="https://example.com/a" onerror="alert(1)"><a href="javascript:alert(1)">bad</a><iframe src="https://example.com"></iframe>');
      assert(!/script|onerror|javascript:|iframe/.test(safe), 'Unsafe HTML removed');
      assert(noteHtml('# Export', 'rtl').includes('dir="rtl"') && noteHtml('# Export', 'rtl').includes('<h1>Export</h1>'), 'Standalone HTML export');
      const exports = [];
      const originalCreate = URL.createObjectURL;
      const originalClick = HTMLAnchorElement.prototype.click;
      URL.createObjectURL = blob => { exports.push({ blob }); return originalCreate(blob); };
      HTMLAnchorElement.prototype.click = function () { exports[exports.length - 1].name = this.download; };
      document.getElementById('exportNoteMarkdown').click();
      document.getElementById('exportNoteHtml').click();
      assert(exports[0].name === 'note.md' && await exports[0].blob.text() === editor.value, 'Markdown export preserves source');
      assert(exports[1].name === 'note.html' && (await exports[1].blob.text()).includes('dir="rtl"'), 'HTML download preserves direction');
      URL.createObjectURL = originalCreate;
      HTMLAnchorElement.prototype.click = originalClick;
      let rejected = false; try { noteTable(0, 3); } catch { rejected = true; }
      assert(rejected, 'Invalid table dimensions rejected');
      const picker = document.getElementById('noteTemplate');
      const manager = document.getElementById('manageNoteTemplate');
      const name = document.getElementById('noteTemplateName');
      const content = document.getElementById('noteTemplateContent');
      const form = document.getElementById('noteTemplateForm');
      document.getElementById('newNoteTemplate').click();
      name.value = 'Custom template'; content.value = '# Custom {{date}} {{date}}';
      form.dispatchEvent(new Event('submit', { cancelable: true }));
      const customId = picker.value;
      assert(picker.selectedOptions[0].textContent === 'Custom template', 'New template available');
      name.value = 'Edited template'; content.value = '# Edited {{date}} {{date}}';
      form.dispatchEvent(new Event('submit', { cancelable: true }));
      assert(picker.value === customId && picker.selectedOptions[0].textContent === 'Edited template', 'Template edited');
      const beforeInsert = editor.value;
      editor.setSelectionRange(editor.value.length, editor.value.length);
      document.getElementById('insertNoteTemplate').click();
      assert(editor.value.startsWith(beforeInsert) && editor.value.includes('# Edited') && !editor.value.includes('{{date}}'), 'Custom template insertion and dates');
      const dynamic = noteDynamicValues(new Date(2026, 9, 3, 13, 28, 40));
      assert(dynamic.jDate === '1405/07/11' && dynamic.jFullDatetime.includes(dynamic.jDate), 'Jalali date and datetime');
      for (const key of ['date', 'jDate', 'time', 'jFullDatetime', 'fullDateTime']) assert(typeof dynamic[key] === 'string' && dynamic[key], 'Dynamic value ' + key);
      assert(resolveNoteFields('{{jira}} {{missing}}', { jira: 'https://example.com' }) === 'https://example.com {{missing}}', 'Static and unknown placeholders');
      assert(resolveNoteFields('{{jira}}', { jira: '{{date}}' }) === '{{date}}', 'Field values do not expand recursively');
      let invalid = false; try { validateNoteFields([{ key: 'date', value: '' }]); } catch { invalid = true; }
      assert(invalid, 'Dynamic keys reserved');
      invalid = false; try { validateNoteFields([{ key: 'jira', value: '' }, { key: 'jira', value: '' }]); } catch { invalid = true; }
      assert(invalid, 'Duplicate field keys rejected');
      document.getElementById('manageNoteTemplatesBtn').click();
      const dialog = document.getElementById('noteTemplateDialog');
      assert(dialog.open && dialog.matches(':modal'), 'Template manager is modal');
      document.getElementById('addNoteTemplateField').click();
      document.querySelector('.template-field-key').value = 'jira';
      document.querySelector('.template-field-value').value = 'https://example.com/default';
      content.value = '# Edited {{jira}} {{jDate}} {{time}} {{jFullDatetime}} {{fullDateTime}}';
      form.dispatchEvent(new Event('submit', { cancelable: true }));
      assert(document.querySelector('.template-field-key').value === 'jira', 'Template fields retained after save');
      document.getElementById('closeNoteTemplates').click();
      assert(!dialog.open, 'Modal closes');
      editor.setSelectionRange(editor.value.length, editor.value.length);
      document.getElementById('insertNoteTemplate').click();
      const jira = document.querySelector('#noteFields input[data-key="jira"]');
      assert(jira && jira.value === 'https://example.com/default', 'Default field displayed above editor');
      jira.value = '[Jira](https://example.com/issue)'; jira.dispatchEvent(new Event('input'));
      assert(editor.value.includes('{{jira}}') && !preview.textContent.includes('{{jira}}'), 'Editor retains placeholder; preview resolves it');
      assert(preview.querySelector('a[href="https://example.com/issue"]'), 'Markdown field renders as a link');
      const renderedExports = [];
      URL.createObjectURL = blob => { renderedExports.push(blob); return originalCreate(blob); };
      HTMLAnchorElement.prototype.click = function () {};
      document.getElementById('exportNoteMarkdown').click(); document.getElementById('exportNoteHtml').click();
      assert((await renderedExports[0].text()).includes('[Jira](https://example.com/issue)') && !(await renderedExports[0].text()).includes('{{jira}}'), 'Markdown export resolves fields');
      assert((await renderedExports[1].text()).includes('href="https://example.com/issue"'), 'HTML export resolves fields');
      URL.createObjectURL = originalCreate; HTMLAnchorElement.prototype.click = originalClick;
      let copied = null;
      const originalWrite = navigator.clipboard.writeText;
      navigator.clipboard.writeText = async text => { copied = text; };
      const copyButton = document.getElementById('copyNoteMarkdown');
      copyButton.click(); await Promise.resolve();
      assert(copied === await renderedExports[0].text(), 'Clipboard matches resolved Markdown export');
      assert(document.getElementById('noteStatus').textContent.includes('copied') && !copyButton.disabled, 'Copy success feedback');
      navigator.clipboard.writeText = async () => { throw new Error('Clipboard unavailable'); };
      copyButton.click(); await Promise.resolve();
      assert(document.getElementById('noteStatus').textContent.includes('Could not copy') && !copyButton.disabled, 'Copy failure feedback');
      navigator.clipboard.writeText = originalWrite;
      const teamsContent = noteTeamsContent('Hi\\n\\n[This is a test link](https://google.com/ "https://google.com/")\\n\\nBye', 'rtl');
      assert(teamsContent.html.includes('href="https://google.com/"') && teamsContent.html.includes('dir="rtl"'), 'Teams link and direction');
      assert(teamsContent.text.includes('This is a test link (https://google.com/)') && teamsContent.text.includes('Hi') && teamsContent.text.includes('Bye'), 'Teams readable fallback');
      const originalRichWrite = navigator.clipboard.write;
      let teamsItems;
      navigator.clipboard.write = async items => { teamsItems = items; };
      const teamsButton = document.getElementById('copyNoteTeams');
      teamsButton.click(); await Promise.resolve();
      const teamsHtml = await (await teamsItems[0].getType('text/html')).text();
      const teamsText = await (await teamsItems[0].getType('text/plain')).text();
      assert(teamsHtml.includes('href="https://example.com/issue"') && !teamsHtml.includes('{{jira}}'), 'Teams clipboard resolves field links');
      assert(teamsText.includes('Jira (https://example.com/issue)'), 'Teams plain clipboard contains URL');
      assert(!teamsButton.disabled && document.getElementById('noteStatus').textContent.includes('Copied for Teams'), 'Teams success feedback');
      navigator.clipboard.write = async () => { throw new Error('Clipboard unavailable'); };
      teamsButton.click(); await Promise.resolve();
      assert(!teamsButton.disabled && document.getElementById('noteStatus').textContent.includes('Could not copy for Teams'), 'Teams failure feedback');
      navigator.clipboard.write = originalRichWrite;


      manager.value = 'daily'; manager.dispatchEvent(new Event('change'));
      const beforeDelete = editor.value;
      document.getElementById('deleteNoteTemplate').click();
      assert(![...picker.options].some(option => option.value === 'daily') && editor.value === beforeDelete, 'Delete preserves note');
      return 'Note and template checks passed';
    })()`);
    await window.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await window.webContents.executeJavaScript(`if (!document.getElementById('noteEditor').value.includes('# Meeting notes') || document.getElementById('noteEditor').dir !== 'rtl') throw new Error('Note did not survive reload');`);
    await window.webContents.executeJavaScript(`(() => {
      const picker = document.getElementById('noteTemplate');
      if (![...picker.options].some(option => option.textContent === 'Edited template') || [...picker.options].some(option => option.value === 'daily')) throw new Error('Template changes did not survive reload');
      const jira = document.querySelector('#noteFields input[data-key="jira"]');
      if (!jira || jira.value !== '[Jira](https://example.com/issue)' || !document.getElementById('notePreview').querySelector('a[href="https://example.com/issue"]')) throw new Error('Note field values did not survive reload');
      const edited = JSON.parse(localStorage.getItem(NOTE_TEMPLATES_KEY)).find(item => item.name === 'Edited template');
      if (edited.fields[0].key !== 'jira') throw new Error('Template field definitions did not persist');
      const count = document.getElementById('manageNoteTemplate').options.length;
      for (let i = 0; i < count; i++) document.getElementById('deleteNoteTemplate').click();
      if (!document.getElementById('insertNoteTemplate').disabled || !document.getElementById('deleteNoteTemplate').disabled) throw new Error('Empty template state');
    })()`);
    const reloaded = new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    window.reload();
    await reloaded;
    await window.webContents.executeJavaScript(`if (!document.getElementById('insertNoteTemplate').disabled) throw new Error('Deleted templates restored after reload');`);
    console.log(result + '; reload persistence and empty templates passed');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
});
